language: node_js
node_js:
  - '0.11.16'
  - '0.11.15'
  - '0.11.14'
  - '0.11.13'
  - '0.11.12'
  - '0.11'
  - '0.10.36'
  - '0.10.35'
  - '0.10.34'
  - '0.10.33'
  - '0.10'
  - 'iojs-1.0.0'
  - 'iojs-1.0.1'
  - 'iojs-1.0.2'
  - 'iojs-1.0.3'
  - 'iojs-1.0.4'
  - 'iojs-1.0'
  - 'iojs-1.1'
script: "npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
