environment:
  node_pre_gyp_qn_accessKeyId:
    secure: aS9PiP9UeMGyiI7hDlSDle8WNqfOX7vzSybFmiW29pYPEk+L3pCUUjke6YYDwQUB
  node_pre_gyp_qn_secretAccessKey:
    secure: 32tbTZ5nzLD3XeP32imF28QLaUiS7rRsuskckvk93YptYeeYm2tv7oxRyfcKqfoR
  matrix:
    # - nodejs_version: 0.11.14
    #   msvs_toolset: 12
    - nodejs_version: 0.11.16
      msvs_toolset: 12
    - nodejs_version: 0.11.15
      msvs_toolset: 12
    - nodejs_version: 0.11.13
      msvs_toolset: 12
    - nodejs_version: "0.10"
      msvs_toolset: 12
    # - nodejs_version: "1.1"
    # - nodejs_version: "1.0"
    #   msvs_toolset: 12
    # - nodejs_version: "0.12"
    #   msvs_toolset: 12

platform:
  - x86

install:
  # add local node to path (since we install it for msvs_toolset == 14)
  - SET PATH=%CD%;%PATH%;
  # add local node-pre-gyp dir to path
  - SET PATH=node_modules\.bin;%PATH%
  # use 64 bit python if platform is 64 bit
  - if "%platform%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - SET ARCHPATH=
  - if %platform% == x64 (SET ARCHPATH=x64/)
  # install node version per visual studio toolset
  - powershell Install-Product node $env:nodejs_version $env:platform
  - SET PATH=C:\Program Files (x86)\MSBuild\%msvs_toolset%.0\bin;%PATH%
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\bin;%PATH%
  - if %platform% == x64 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64
  - if %platform% == x86 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64_x86
  - node -v
  - npm -v
  - npm install --build-from-source
  - npm test
  # make commit message env var shorter
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - if not "%CM%" == "%CM:[republish binary]=%" npm run unpublish-binary
  - if not "%CM%" == "%CM:[republish binary]=%" npm run publish-binary
  - if not "%CM%" == "%CM:[republish binary]=%" npm run test-publish-binary
  - if not "%CM%" == "%CM:[publish binary]=%" npm run publish-binary
  - if not "%CM%" == "%CM:[publish binary]=%" npm run test-publish-binary
  - npm run list-binary

build: OFF
test: OFF
deploy: OFF
